# Generated by Django 4.2.2 on 2023-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands_app', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('fundacja', 'fundacja'), ('organizacja pozarządowa', 'organizacja pozarządowa'), ('zbiórka lokalna', 'zbiórka lokalna')], default='fundacja', max_length=64),
        ),
    ]
