# Generated by Django 4.2.2 on 2023-07-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands_app', '0004_institution_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name_plural': 'Institutions'},
        ),
    ]
